import Foundation

enum AutoPasteDestination: Int {
    case apWord = 1
    case apPowerPoint = 2
    case apPages = 3
    case apNumbers = 4
    case apKeynote = 5
}

typealias Profile = NSDictionary
typealias MutableProfile = NSMutableDictionary

let AnnotationHeader = "%%TeX2img Document\n"
let CUI_PATH = "/usr/local/bin/tex2img"
let SVG_PREVIEWER = "/Applications/Gapplin.app"
let GAPPLIN_URL = "macappstore://apps.apple.com/app/id768053424?mt=12"
let TargetExtensionsArray: [String] = ["eps", "pdf", "svg", "svgz", "jpg", "png", "gif", "tiff", "bmp"]
let ImportExtensionsArray: [String] = ["eps", "pdf", "svg", "svgz", "jpg", "png", "gif", "tiff", "bmp", "tex"]
let InputExtensionsArray: [String] = ["tex", "pdf", "ps", "eps"]
let BitmapExtensionsArray: [String] = ["png", "jpg", "gif", "tiff", "bmp"]
let MergeableExtensionsArray: [String] = ["pdf", "tiff", "gif", "svg", "svgz"]
let ProfileNamesKey = "profileNames"
let ProfilesKey = "profiles"
let XKey = "x"
let YKey = "y"
let MainWindowWidthKey = "mainWindowWidth"
let MainWindowHeightKey = "mainWindowHeight"
let OutputFileKey = "outputFile"
let AutoRestoreSourceKey = "autoRestoreSource"
let ShowOutputWindowKey = "showOutputDrawer"
let SendNotificationKey = "sendNotification"
let PreviewKey = "preview"
let DeleteTmpFileKey = "deleteTmpFile"
let CopyToClipboardKey = "copyToClipboard"
let AutoPasteKey = "autoPaste"
let AutoPasteDestinationKey = "autoPasteDestination"
let EmbedInIllustratorKey = "embedInIllustrator"
let UngroupKey = "ungroup"
let TransparentKey = "transparent"
let PlainTextKey = "plainText"
let GetOutlineKey = "getOutline"
let DeleteDisplaySizeKey = "deleteDisplaySize"
let MergeOutputsKey = "mergeOutputs"
let KeepPageSizeKey = "keepPageSize"
let IgnoreErrorKey = "ignoreError"
let UtfExportKey = "utfExport"
let LatexPathKey = "platexPath"
let DviDriverPathKey = "dvipdfmxPath"
let GsPathKey = "gsPath"
let GuessCompilationKey = "guessCompilation"
let NumberOfCompilationKey = "numberOfCompilation"
let ResolutionKey = "resolution"
let DPIKey = "dpi"
let LeftMarginKey = "leftMargin"
let RightMarginKey = "rightMargin"
let TopMarginKey = "topMargin"
let BottomMarginKey = "bottomMargin"
let UnitKey = "unit"
let PriorityKey = "priority"
let EmbedSourceKey = "embedSource"
let TabWidthKey = "tabWidth"
let TabIndentKey = "tabIndent"
let WrapLineKey = "warpLines"
let CommandCompletionKeyKey = "commandCompletionKey"
let FillColorKey = "fillColor"
let ForegroundColorForLightModeKey = "foregroundColor"
let BackgroundColorForLightModeKey = "backgroundColor"
let CursorColorForLightModeKey = "cursorColor"
let BraceColorForLightModeKey = "braceColor"
let CommentColorForLightModeKey = "commentColor"
let CommandColorForLightModeKey = "commandColor"
let InvisibleColorForLightModeKey = "invisibleColor"
let HighlightedBraceColorForLightModeKey = "highlightedBraceColor"
let EnclosedContentBackgroundColorForLightModeKey = "enclosedContentBackgroundColor"
let FlashingBackgroundColorForLightModeKey = "flashingBackgroundColor"
let ConsoleForegroundColorForLightModeKey = "consoleForegroundColor"
let ConsoleBackgroundColorForLightModeKey = "consoleBackgroundColor"
let ForegroundColorForDarkModeKey = "foregroundColorForDarkMode"
let BackgroundColorForDarkModeKey = "backgroundColorForDarkMode"
let CursorColorForDarkModeKey = "cursorColorForDarkMode"
let BraceColorForDarkModeKey = "braceColorForDarkMode"
let CommentColorForDarkModeKey = "commentColorForDarkMode"
let CommandColorForDarkModeKey = "commandColorForDarkMode"
let InvisibleColorForDarkModeKey = "invisibleColorForDarkMode"
let HighlightedBraceColorForDarkModeKey = "highlightedBraceColorForDarkMode"
let EnclosedContentBackgroundColorForDarkModeKey = "enclosedContentBackgroundColorForDarkMode"
let FlashingBackgroundColorForDarkModeKey = "flashingBackgroundColorForDarkMode"
let ConsoleForegroundColorForDarkModeKey = "consoleForegroundColorForDarkMode"
let ConsoleBackgroundColorForDarkModeKey = "consoleBackgroundColorForDarkMode"
let MakeatletterEnabledKey = "makeatletterEnabled"
let WorkingDirectoryTypeKey = "workingDirectoryType"
let WorkingDirectoryPathKey = "workingDirectoryPath"
let WorkingDirectoryTmp = 1
let WorkingDirectoryFile = 2
let WorkingDirectoryCurrent = 3
let ColorPalleteColorKey = "colorPalleteColor"
let ConvertYenMarkKey = "convertYenMark"
let RichTextKey = "copyAsRichText"
let FlashInMovingKey = "flashInMoving"
let HighlightContentKey = "highlightContent"
let BeepKey = "beep"
let FlashBackgroundKey = "flashBackground"
let CheckBraceKey = "checkBrace"
let CheckBracketKey = "checkBracket"
let CheckSquareBracketKey = "checkSquareBracket"
let CheckParenKey = "checkParen"
let AutoCompleteKey = "autoComplete"
let AutoIndentKey = "autoIndent"
let ShowTabCharacterKey = "showTabCharacter"
let ShowSpaceCharacterKey = "showSpaceCharacter"
let ShowFullwidthSpaceCharacterKey = "showFullwidthSpaceCharacter"
let ShowNewLineCharacterKey = "showNewLineCharacter"
let SourceFontNameKey = "sourceFontName"
let SourceFontSizeKey = "sourceFontSize"
let PreambleKey = "preamble"
let SourceBodyKey = "sourceBody"
let InputMethodKey = "inputMethod"
let InputSourceFilePathKey = "inputSourceFilePath"
let EncodingKey = "encoding"
let EpstopdfPathKey = "epstopdfPath"
let MudrawPathKey = "mudrawPath"
let PdftopsPathKey = "pdftopsPath"
let QuietKey = "quiet"
let AutoDetectionTargetKey = "autoDetectionTarget"
let SpaceCharacterKindKey = "spaceCharacterKind"
let FullwidthSpaceCharacterKindKey = "fullwidthSpaceCharacterKind"
let ReturnCharacterKindKey = "returnCharacterKind"
let TabCharacterKindKey = "tabCharacterKind"
let PageBoxKey = "pageBox"
let LoopCountKey = "loopCount"
let DelayKey = "delay"
let ControllerKey = "controller"
let TeX2imgVersionKey = "TeX2imgVersion"
let ESCAPE_KEY = 1
let TAB_KEY = 2
let LIGHTMODE_TAG = 1
let DARKMODE_TAG = 2
let PX_UNIT_TAG = 1
let BP_UNIT_TAG = 2
let QUALITY_PRIORITY_TAG = 1
let SPEED_PRIORITY_TAG = 2
let DIRECT_INPUT_TAG = 0
let INPUT_FILE_TAG = 1
let COLOR_TAG = 1
let TEXTCOLOR_TAG = 2
let COLORBOX_TAG = 3
let DEFINECOLOR_TAG = 4
let CommentOutTag = 1
let UncommentTag = 2
let ShiftRightTag = 3
let ShiftLeftTag = 4
let NFC_Tag = 1
let Modified_NFC_Tag = 2
let NFD_Tag = 3
let Modified_NFD_Tag = 4
let NFKC_Tag = 5
let NFKD_Tag = 6
let NFKC_CF_Tag = 7
let HiraganaToKatakana_Tag = 1
let KatakanaToHiragana_Tag = 2
let FullwidthDigitsToHalfwidthDigits_Tag = 3
let HalfwidthDigitsToFullwidthDigits_Tag = 4
let FullwidthAlphabetsToHalfwidthAlphabets_Tag = 5
let HalfwidthAlphabetsToFullwidthAlphabets_Tag = 6
let UnicodeCharactersToAJMacros_Tag = 7
let AJMacrosToUnicodeCharacters_Tag = 8
let UnicodeCharactersToUTF_Tag = 9
let UTFToUnicodeCharacters_Tag = 10
let FullwidthQuotesToHalfwidthQuotes_Tag = 11
let TeXtoDVItoPDF = 1
let TeXtoPDF = 2
let PTEX_ENCODING_NONE = "none"
let PTEX_ENCODING_UTF8 = "utf8"
let PTEX_ENCODING_SJIS = "sjis"
let PTEX_ENCODING_JIS = "jis"
let PTEX_ENCODING_EUC = "euc"
let EA_Key = "com.loveinequality.TeX2img"
var GUI_PATHS: [String] {
    [
        (NSHomeDirectory() as NSString).appendingPathComponent("Desktop"),
        (NSHomeDirectory() as NSString).appendingPathComponent("Applications"),
        NSHomeDirectory(),
        "/Applications",
        "/Applications/TeXLive",
    ]
}
