import Foundation

let ligToAjLigStringReplacements: [(String, String, Bool)] = [
    ("㍾", "\\ajLig{明治}", true),
    ("㍽", "\\ajLig{大正}", true),
    ("㍼", "\\ajLig{昭和}", true),
    ("㍻", "\\ajLig{平成}", true),
    ("㋿", "\\ajLig{令和}", true),
    ("㍉", "\\ajLig{ミリ}", true),
    ("㌔", "\\ajLig{キロ}", true),
    ("㌢", "\\ajLig{センチ}", true),
    ("㍍", "\\ajLig{メートル}", true),
    ("㌘", "\\ajLig{グラム}", true),
    ("㌧", "\\ajLig{トン}", true),
    ("㌃", "\\ajLig{アール}", true),
    ("㌶", "\\ajLig{ヘクタール}", true),
    ("㍑", "\\ajLig{リットル}", true),
    ("㍗", "\\ajLig{ワット}", true),
    ("㌍", "\\ajLig{カロリー}", true),
    ("㌦", "\\ajLig{ドル}", true),
    ("㌣", "\\ajLig{セント}", true),
    ("㌫", "\\ajLig{パーセント}", true),
    ("㍊", "\\ajLig{ミリバール}", true),
    ("㌻", "\\ajLig{ページ}", true),
    ("㌖", "\\ajLig{キロメートル}", true),
    ("㌕", "\\ajLig{キログラム}", true),
    ("㌃", "\\ajLig{アール}", true),
    ("㍗", "\\ajLig{ワット}", true),
    ("㍂", "\\ajLig{ホーン}", true),
    ("㌹", "\\ajLig{ヘルツ}", true),
    ("㌻", "\\ajLig{ページ}", true),
    ("㌀", "\\ajLig{アパート}", true),
    ("㌱", "\\ajLig{ビル}", true),
    ("㍇", "\\ajLig{マンション}", true),
    ("㌞", "\\ajLig{コーポ}", true),
    ("㌪", "\\ajLig{ハイツ}", true),
    ("㍿", "\\ajLig{株式会社}", true),
    ("㌅", "\\ajLig{インチ}", true),
    ("㌳", "\\ajLig{フィート}", true),
    ("㍎", "\\ajLig{ヤード}", true),
    ("㌹", "\\ajLig{ヘルツ}", true),
    ("㍂", "\\ajLig{ホーン}", true),
    ("㌞", "\\ajLig{コーポ}", true),
    ("㌪", "\\ajLig{ハイツ}", true),
    ("㌁", "\\ajLig{アルファ}", true),
    ("㌂", "\\ajLig{アンペア}", true),
    ("㌄", "\\ajLig{イニング}", true),
    ("㌆", "\\ajLig{ウォン}", true),
    ("㌈", "\\ajLig{エーカー}", true),
    ("㌇", "\\ajLig{エスクード}", true),
    ("㌊", "\\ajLig{オーム}", true),
    ("㌉", "\\ajLig{オンス}", true),
    ("㌌", "\\ajLig{カラット}", true),
    ("㌎", "\\ajLig{ガロン}", true),
    ("㌏", "\\ajLig{ガンマ}", true),
    ("㌐", "\\ajLig{ギガ}", true),
    ("㌑", "\\ajLig{ギニー}", true),
    ("㌒", "\\ajLig{キュリー}", true),
    ("㌓", "\\ajLig{ギルダー}", true),
    ("㌗", "\\ajLig{キロワット}", true),
    ("㌙", "\\ajLig{グラムトン}", true),
    ("㌚", "\\ajLig{クルゼイロ}", true),
    ("㌛", "\\ajLig{クローネ}", true),
    ("㌜", "\\ajLig{ケース}", true),
    ("㌝", "\\ajLig{コルナ}", true),
    ("㌟", "\\ajLig{サイクル}", true),
    ("㌠", "\\ajLig{サンチーム}", true),
    ("㌡", "\\ajLig{シリング}", true),
    ("㌤", "\\ajLig{ダース}", true),
    ("㌥", "\\ajLig{デシ}", true),
    ("㌨", "\\ajLig{ナノ}", true),
    ("㌩", "\\ajLig{ノット}", true),
    ("㌭", "\\ajLig{バーレル}", true),
    ("㌮", "\\ajLig{ピアストル}", true),
    ("㌯", "\\ajLig{ピクル}", true),
    ("㌰", "\\ajLig{ピコ}", true),
    ("㌲", "\\ajLig{ファラッド}", true),
    ("㌴", "\\ajLig{ブッシェル}", true),
    ("㌵", "\\ajLig{フラン}", true),
    ("㌼", "\\ajLig{ベータ}", true),
    ("㌷", "\\ajLig{ペソ}", true),
    ("㌸", "\\ajLig{ペニヒ}", true),
    ("㌺", "\\ajLig{ペンス}", true),
    ("㌽", "\\ajLig{ポイント}", true),
    ("㍁", "\\ajLig{ホール}", true),
    ("㌾", "\\ajLig{ボルト}", true),
    ("㌿", "\\ajLig{ホン}", true),
    ("㍀", "\\ajLig{ポンド}", true),
    ("㍃", "\\ajLig{マイクロ}", true),
    ("㍄", "\\ajLig{マイル}", true),
    ("㍅", "\\ajLig{マッハ}", true),
    ("㍆", "\\ajLig{マルク}", true),
    ("㍈", "\\ajLig{ミクロン}", true),
    ("㍋", "\\ajLig{メガ}", true),
    ("㍌", "\\ajLig{メガトン}", true),
    ("㍏", "\\ajLig{ヤール}", true),
    ("㍐", "\\ajLig{ユアン}", true),
    ("㍒", "\\ajLig{リラ}", true),
    ("㍔", "\\ajLig{ルーブル}", true),
    ("㍓", "\\ajLig{ルピー}", true),
    ("㍕", "\\ajLig{レム}", true),
    ("㍖", "\\ajLig{レントゲン}", true),
    ("㊤", "\\ajLig{○上}", true),
    ("㊥", "\\ajLig{○中}", true),
    ("㊦", "\\ajLig{○下}", true),
    ("㊧", "\\ajLig{○左}", true),
    ("㊨", "\\ajLig{○右}", true),
    ("〶", "\\ajLig{○〒}", true),
    ("㊰", "\\ajLig{○夜}", true),
    ("㊭", "\\ajLig{○企}", true),
    ("㊩", "\\ajLig{○医}", true),
    ("㊯", "\\ajLig{○協}", true),
    ("㊔", "\\ajLig{○名}", true),
    ("㊪", "\\ajLig{○宗}", true),
    ("㊘", "\\ajLig{○労}", true),
    ("㊫", "\\ajLig{○学}", true),
    ("㊒", "\\ajLig{○有}", true),
    ("㊑", "\\ajLig{○株}", true),
    ("㊓", "\\ajLig{○社}", true),
    ("㊬", "\\ajLig{○監}", true),
    ("㊮", "\\ajLig{○資}", true),
    ("㊖", "\\ajLig{○財}", true),
    ("㊞", "\\ajLig{○印}", true),
    ("㊙", "\\ajLig{○秘}", true),
    ("㊝", "\\ajLig{○優}", true),
    ("㊟", "\\ajLig{○注}", true),
    ("㊠", "\\ajLig{○項}", true),
    ("㊡", "\\ajLig{○休}", true),
    ("㊛", "\\ajLig{○女}", true),
    ("㊚", "\\ajLig{○男}", true),
    ("㊣", "\\ajLig{○正}", true),
    ("㊢", "\\ajLig{○写}", true),
    ("㊗", "\\ajLig{○祝}", true),
    ("㊜", "\\ajLig{○適}", true),
    ("㊕", "\\ajLig{○特}", true),
    ("㈱", "\\ajLig{(株)}", true),
    ("㈲", "\\ajLig{(有)}", true),
    ("㈹", "\\ajLig{(代)}", true),
    ("㉃", "\\ajLig{(至)}", true),
    ("㈽", "\\ajLig{(企)}", true),
    ("㈿", "\\ajLig{(協)}", true),
    ("㈴", "\\ajLig{(名)}", true),
    ("㈸", "\\ajLig{(労)}", true),
    ("㈳", "\\ajLig{(社)}", true),
    ("㈼", "\\ajLig{(監)}", true),
    ("㉂", "\\ajLig{(自)}", true),
    ("㈾", "\\ajLig{(資)}", true),
    ("㈶", "\\ajLig{(財)}", true),
    ("㈵", "\\ajLig{(特)}", true),
    ("㈻", "\\ajLig{(学)}", true),
    ("㉀", "\\ajLig{(祭)}", true),
    ("㈺", "\\ajLig{(呼)}", true),
    ("㈷", "\\ajLig{(祝)}", true),
    ("㉁", "\\ajLig{(休)}", true),
    ("ゔ", "\\ajLig{う゛}", true),
    ("ヷ", "\\ajLig{ワ゛}", true),
    ("ヸ", "\\ajLig{ヰ゛}", true),
    ("ヹ", "\\ajLig{ヱ゛}", true),
    ("ヺ", "\\ajLig{ヲ゛}", true),
    ("ゕ", "\\ajLig{小か}", true),
    ("ゖ", "\\ajLig{小け}", true),
    ("㎜", "\\ajLig{mm}", true),
    ("㎝", "\\ajLig{cm}", true),
    ("㎞", "\\ajLig{km}", true),
    ("㎎", "\\ajLig{mg}", true),
    ("㎏", "\\ajLig{kg}", true),
    ("㏄", "\\ajLig{cc}", true),
    ("㎡", "\\ajLig{m2}", true),
    ("№", "\\ajLig{No.}", true),
    ("㏍", "\\ajLig{K.K.}", true),
    ("㎠", "\\ajLig{cm2}", true),
    ("㎢", "\\ajLig{km2}", true),
    ("㎤", "\\ajLig{cm3}", true),
    ("㎥", "\\ajLig{m3}", true),
    ("㎗", "\\ajLig{dl}", true),
    ("ℓ", "\\ajLig{l}", true),
    ("㎘", "\\ajLig{kl}", true),
    ("㎳", "\\ajLig{ms}", true),
    ("㎲", "\\ajLig{micros}", true),
    ("㎱", "\\ajLig{ns}", true),
    ("㎰", "\\ajLig{ps}", true),
    ("㎅", "\\ajLig{KB}", true),
    ("㎆", "\\ajLig{MB}", true),
    ("㎇", "\\ajLig{GB}", true),
    ("㏋", "\\ajLig{HP}", true),
    ("㎐", "\\ajLig{Hz}", true),
    ("㎖", "\\ajLig{ml}", true),
    ("℡", "\\ajLig{Tel}", true),
    ("㏌", "\\ajLig{in}", true),
    ("㎟", "\\ajLig{mm2}", true),
    ("㎣", "\\ajLig{mm3}", true),
    ("㎦", "\\ajLig{km3}", true),
    ("㎈", "\\ajLig{cal}", true),
    ("㎉", "\\ajLig{kcal}", true),
    ("㏈", "\\ajLig{dB}", true),
    ("℉", "\\ajLig{F}", true),
    ("㏂", "\\ajLig{a.m.}", true),
    ("㏘", "\\ajLig{p.m.}", true),
    ("㍱", "\\ajLig{hPa}", true),
    ("㎍", "\\ajLig{microg}", true),
    ("㎛", "\\ajLig{microm}", true),
    ("㏗", "\\ajLig{pH}", true),
    ("〄", "\\ajLig{JIS}", true),
    ("℧", "\\ajLig{mho}", true),
    ("€", "\\ajLig{euro}", true),
    ("‼", "\\ajLig{!!}", true),
    ("⁇", "\\ajLig{??}", true),
    ("⁈", "\\ajLig{?!}", true),
    ("⁉", "\\ajLig{!?}", true),
    ("〼", "\\ajMasu ", false),
    ("ゟ", "\\ajYori ", false),
    ("ヿ", "\\ajKoto ", false),
    ("〽", "\\ajUta ", false),
    ("⌘", "\\ajCommandKey ", false),
    ("⏎", "\\ajReturnKey ", false),
    ("✓", "\\ajCheckmark ", false),
    ("␣", "\\ajVisibleSpace ", false),
    ("☗", "\\ajSenteMark ", false),
    ("☖", "\\ajGoteMark ", false),
    ("♣", "\\ajClub ", false),
    ("♡", "\\ajHeart ", false),
    ("♠", "\\ajSpade ", false),
    ("♢", "\\ajDiamond ", false),
    ("♧", "\\ajvarClub ", false),
    ("♥", "\\ajvarHeart ", false),
    ("♤", "\\ajvarSpade ", false),
    ("♦", "\\ajvarDiamond ", false),
    ("☎", "\\ajPhone ", false),
    ("〠", "\\ajPostal ", false),
    ("〶", "\\ajvarPostal ", false),
    ("☀", "\\ajSun ", false),
    ("☁", "\\ajCloud ", false),
    ("☂", "\\ajUmbrella ", false),
    ("☃", "\\ajSnowman ", false),
    ("〄", "\\ajJIS ", false),
    ("♨", "\\ajHotSpring ", false),
    ("﹆", "\\ajWhiteSesame ", false),
    ("﹅", "\\ajBlackSesame ", false),
    ("❀", "\\ajWhiteFlorette ", false),
    ("✿", "\\ajBlackFlorette ", false),
    ("髙", "\\ajHashigoTaka ", false),
    ("𠮷", "\\ajTsuchiYoshi ", false),
    ("﨑", "\\ajTatsuSaki ", false),
    ("濵", "\\ajMayuHama ", false),
]

let ajLigToLigStringReplacements: [(String, String, Bool)] = [
    ("\\ajLig{明治}", "㍾", false),
    ("\\ajLig{大正}", "㍽", false),
    ("\\ajLig{昭和}", "㍼", false),
    ("\\ajLig{平成}", "㍻", false),
    ("\\ajLig{令和}", "㋿", false),
    ("\\ajLig{ミリ}", "㍉", false),
    ("\\ajLig{キロ}", "㌔", false),
    ("\\ajLig{センチ}", "㌢", false),
    ("\\ajLig{メートル}", "㍍", false),
    ("\\ajLig{グラム}", "㌘", false),
    ("\\ajLig{トン}", "㌧", false),
    ("\\ajLig{アール}", "㌃", false),
    ("\\ajLig{ヘクタール}", "㌶", false),
    ("\\ajLig{リットル}", "㍑", false),
    ("\\ajLig{ワット}", "㍗", false),
    ("\\ajLig{カロリー}", "㌍", false),
    ("\\ajLig{ドル}", "㌦", false),
    ("\\ajLig{セント}", "㌣", false),
    ("\\ajLig{パーセント}", "㌫", false),
    ("\\ajLig{ミリバール}", "㍊", false),
    ("\\ajLig{ページ}", "㌻", false),
    ("\\ajLig{キロメートル}", "㌖", false),
    ("\\ajLig{キログラム}", "㌕", false),
    ("\\ajLig{アール}", "㌃", false),
    ("\\ajLig{ワット}", "㍗", false),
    ("\\ajLig{ホーン}", "㍂", false),
    ("\\ajLig{ヘルツ}", "㌹", false),
    ("\\ajLig{ページ}", "㌻", false),
    ("\\ajLig{アパート}", "㌀", false),
    ("\\ajLig{ビル}", "㌱", false),
    ("\\ajLig{マンション}", "㍇", false),
    ("\\ajLig{コーポ}", "㌞", false),
    ("\\ajLig{ハイツ}", "㌪", false),
    ("\\ajLig{株式会社}", "㍿", false),
    ("\\ajLig{インチ}", "㌅", false),
    ("\\ajLig{フィート}", "㌳", false),
    ("\\ajLig{ヤード}", "㍎", false),
    ("\\ajLig{ヘルツ}", "㌹", false),
    ("\\ajLig{ホーン}", "㍂", false),
    ("\\ajLig{コーポ}", "㌞", false),
    ("\\ajLig{ハイツ}", "㌪", false),
    ("\\ajLig{アルファ}", "㌁", false),
    ("\\ajLig{アンペア}", "㌂", false),
    ("\\ajLig{イニング}", "㌄", false),
    ("\\ajLig{ウォン}", "㌆", false),
    ("\\ajLig{エーカー}", "㌈", false),
    ("\\ajLig{エスクード}", "㌇", false),
    ("\\ajLig{オーム}", "㌊", false),
    ("\\ajLig{オンス}", "㌉", false),
    ("\\ajLig{カラット}", "㌌", false),
    ("\\ajLig{ガロン}", "㌎", false),
    ("\\ajLig{ガンマ}", "㌏", false),
    ("\\ajLig{ギガ}", "㌐", false),
    ("\\ajLig{ギニー}", "㌑", false),
    ("\\ajLig{キュリー}", "㌒", false),
    ("\\ajLig{ギルダー}", "㌓", false),
    ("\\ajLig{キロワット}", "㌗", false),
    ("\\ajLig{グラムトン}", "㌙", false),
    ("\\ajLig{クルゼイロ}", "㌚", false),
    ("\\ajLig{クローネ}", "㌛", false),
    ("\\ajLig{ケース}", "㌜", false),
    ("\\ajLig{コルナ}", "㌝", false),
    ("\\ajLig{サイクル}", "㌟", false),
    ("\\ajLig{サンチーム}", "㌠", false),
    ("\\ajLig{シリング}", "㌡", false),
    ("\\ajLig{ダース}", "㌤", false),
    ("\\ajLig{デシ}", "㌥", false),
    ("\\ajLig{ナノ}", "㌨", false),
    ("\\ajLig{ノット}", "㌩", false),
    ("\\ajLig{バーレル}", "㌭", false),
    ("\\ajLig{ピアストル}", "㌮", false),
    ("\\ajLig{ピクル}", "㌯", false),
    ("\\ajLig{ピコ}", "㌰", false),
    ("\\ajLig{ファラッド}", "㌲", false),
    ("\\ajLig{ブッシェル}", "㌴", false),
    ("\\ajLig{フラン}", "㌵", false),
    ("\\ajLig{ベータ}", "㌼", false),
    ("\\ajLig{ペソ}", "㌷", false),
    ("\\ajLig{ペニヒ}", "㌸", false),
    ("\\ajLig{ペンス}", "㌺", false),
    ("\\ajLig{ポイント}", "㌽", false),
    ("\\ajLig{ホール}", "㍁", false),
    ("\\ajLig{ボルト}", "㌾", false),
    ("\\ajLig{ホン}", "㌿", false),
    ("\\ajLig{ポンド}", "㍀", false),
    ("\\ajLig{マイクロ}", "㍃", false),
    ("\\ajLig{マイル}", "㍄", false),
    ("\\ajLig{マッハ}", "㍅", false),
    ("\\ajLig{マルク}", "㍆", false),
    ("\\ajLig{ミクロン}", "㍈", false),
    ("\\ajLig{メガ}", "㍋", false),
    ("\\ajLig{メガトン}", "㍌", false),
    ("\\ajLig{ヤール}", "㍏", false),
    ("\\ajLig{ユアン}", "㍐", false),
    ("\\ajLig{リラ}", "㍒", false),
    ("\\ajLig{ルーブル}", "㍔", false),
    ("\\ajLig{ルピー}", "㍓", false),
    ("\\ajLig{レム}", "㍕", false),
    ("\\ajLig{レントゲン}", "㍖", false),
    ("\\ajLig{○上}", "㊤", false),
    ("\\ajLig{○中}", "㊥", false),
    ("\\ajLig{○下}", "㊦", false),
    ("\\ajLig{○左}", "㊧", false),
    ("\\ajLig{○右}", "㊨", false),
    ("\\ajLig{○〒}", "〶", false),
    ("\\ajLig{○夜}", "㊰", false),
    ("\\ajLig{○企}", "㊭", false),
    ("\\ajLig{○医}", "㊩", false),
    ("\\ajLig{○協}", "㊯", false),
    ("\\ajLig{○名}", "㊔", false),
    ("\\ajLig{○宗}", "㊪", false),
    ("\\ajLig{○労}", "㊘", false),
    ("\\ajLig{○学}", "㊫", false),
    ("\\ajLig{○有}", "㊒", false),
    ("\\ajLig{○株}", "㊑", false),
    ("\\ajLig{○社}", "㊓", false),
    ("\\ajLig{○監}", "㊬", false),
    ("\\ajLig{○資}", "㊮", false),
    ("\\ajLig{○財}", "㊖", false),
    ("\\ajLig{○印}", "㊞", false),
    ("\\ajLig{○秘}", "㊙", false),
    ("\\ajLig{○優}", "㊝", false),
    ("\\ajLig{○注}", "㊟", false),
    ("\\ajLig{○項}", "㊠", false),
    ("\\ajLig{○休}", "㊡", false),
    ("\\ajLig{○女}", "㊛", false),
    ("\\ajLig{○男}", "㊚", false),
    ("\\ajLig{○正}", "㊣", false),
    ("\\ajLig{○写}", "㊢", false),
    ("\\ajLig{○祝}", "㊗", false),
    ("\\ajLig{○適}", "㊜", false),
    ("\\ajLig{○特}", "㊕", false),
    ("\\○上", "㊤", false),
    ("\\○中", "㊥", false),
    ("\\○下", "㊦", false),
    ("\\○左", "㊧", false),
    ("\\○右", "㊨", false),
    ("\\○〒", "〶", false),
    ("\\○夜", "㊰", false),
    ("\\○企", "㊭", false),
    ("\\○医", "㊩", false),
    ("\\○協", "㊯", false),
    ("\\○名", "㊔", false),
    ("\\○宗", "㊪", false),
    ("\\○労", "㊘", false),
    ("\\○学", "㊫", false),
    ("\\○有", "㊒", false),
    ("\\○株", "㊑", false),
    ("\\○社", "㊓", false),
    ("\\○監", "㊬", false),
    ("\\○資", "㊮", false),
    ("\\○財", "㊖", false),
    ("\\○印", "㊞", false),
    ("\\○秘", "㊙", false),
    ("\\○優", "㊝", false),
    ("\\○注", "㊟", false),
    ("\\○項", "㊠", false),
    ("\\○休", "㊡", false),
    ("\\○女", "㊛", false),
    ("\\○男", "㊚", false),
    ("\\○正", "㊣", false),
    ("\\○写", "㊢", false),
    ("\\○祝", "㊗", false),
    ("\\○適", "㊜", false),
    ("\\○特", "㊕", false),
    ("\\ajLig{(株)}", "㈱", false),
    ("\\ajLig{(有)}", "㈲", false),
    ("\\ajLig{(代)}", "㈹", false),
    ("\\ajLig{(至)}", "㉃", false),
    ("\\ajLig{(企)}", "㈽", false),
    ("\\ajLig{(協)}", "㈿", false),
    ("\\ajLig{(名)}", "㈴", false),
    ("\\ajLig{(労)}", "㈸", false),
    ("\\ajLig{(社)}", "㈳", false),
    ("\\ajLig{(監)}", "㈼", false),
    ("\\ajLig{(自)}", "㉂", false),
    ("\\ajLig{(資)}", "㈾", false),
    ("\\ajLig{(財)}", "㈶", false),
    ("\\ajLig{(特)}", "㈵", false),
    ("\\ajLig{(学)}", "㈻", false),
    ("\\ajLig{(祭)}", "㉀", false),
    ("\\ajLig{(呼)}", "㈺", false),
    ("\\ajLig{(祝)}", "㈷", false),
    ("\\ajLig{(休)}", "㉁", false),
    ("\\（株）", "㈱", false),
    ("\\（有）", "㈲", false),
    ("\\（代）", "㈹", false),
    ("\\（至）", "㉃", false),
    ("\\（企）", "㈽", false),
    ("\\（協）", "㈿", false),
    ("\\（名）", "㈴", false),
    ("\\（労）", "㈸", false),
    ("\\（社）", "㈳", false),
    ("\\（監）", "㈼", false),
    ("\\（自）", "㉂", false),
    ("\\（資）", "㈾", false),
    ("\\（財）", "㈶", false),
    ("\\（特）", "㈵", false),
    ("\\（学）", "㈻", false),
    ("\\（祭）", "㉀", false),
    ("\\（呼）", "㈺", false),
    ("\\（祝）", "㈷", false),
    ("\\（休）", "㉁", false),
    ("\\ajLig{う゛}", "ゔ", false),
    ("\\ajLig{ワ゛}", "ヷ", false),
    ("\\ajLig{ヰ゛}", "ヸ", false),
    ("\\ajLig{ヱ゛}", "ヹ", false),
    ("\\ajLig{ヲ゛}", "ヺ", false),
    ("\\゛う", "ゔ", false),
    ("\\゛ワ", "ヷ", false),
    ("\\゛ヰ", "ヸ", false),
    ("\\゛ヱ", "ヹ", false),
    ("\\゛ヲ", "ヺ", false),
    ("\\ajLig{小か}", "ゕ", false),
    ("\\ajLig{小け}", "ゖ", false),
    ("\\！か", "ゕ", false),
    ("\\！け", "ゖ", false),
    ("\\ajLig{mm}", "㎜", false),
    ("\\ajLig{cm}", "㎝", false),
    ("\\ajLig{km}", "㎞", false),
    ("\\ajLig{mg}", "㎎", false),
    ("\\ajLig{kg}", "㎏", false),
    ("\\ajLig{cc}", "㏄", false),
    ("\\ajLig{m2}", "㎡", false),
    ("\\ajLig{No.}", "№", false),
    ("\\ajLig{K.K.}", "㏍", false),
    ("\\ajLig{cm2}", "㎠", false),
    ("\\ajLig{km2}", "㎢", false),
    ("\\ajLig{cm3}", "㎤", false),
    ("\\ajLig{m3}", "㎥", false),
    ("\\ajLig{dl}", "㎗", false),
    ("\\ajLig{l}", "ℓ", false),
    ("\\ajLig{kl}", "㎘", false),
    ("\\ajLig{ms}", "㎳", false),
    ("\\ajLig{micros}", "㎲", false),
    ("\\ajLig{ns}", "㎱", false),
    ("\\ajLig{ps}", "㎰", false),
    ("\\ajLig{KB}", "㎅", false),
    ("\\ajLig{MB}", "㎆", false),
    ("\\ajLig{GB}", "㎇", false),
    ("\\ajLig{HP}", "㏋", false),
    ("\\ajLig{Hz}", "㎐", false),
    ("\\ajLig{ml}", "㎖", false),
    ("\\ajLig{Tel}", "℡", false),
    ("\\ajLig{in}", "㏌", false),
    ("\\ajLig{mm2}", "㎟", false),
    ("\\ajLig{mm3}", "㎣", false),
    ("\\ajLig{km3}", "㎦", false),
    ("\\ajLig{cal}", "㎈", false),
    ("\\ajLig{kcal}", "㎉", false),
    ("\\ajLig{dB}", "㏈", false),
    ("\\ajLig{F}", "℉", false),
    ("\\ajLig{a.m.}", "㏂", false),
    ("\\ajLig{p.m.}", "㏘", false),
    ("\\ajLig{hPa}", "㍱", false),
    ("\\ajLig{microg}", "㎍", false),
    ("\\ajLig{microm}", "㎛", false),
    ("\\ajLig{pH}", "㏗", false),
    ("\\ajLig{JIS}", "〄", false),
    ("\\ajLig{mho}", "℧", false),
    ("\\ajLig{euro}", "€", false),
    ("\\ajLig{!!}", "‼", false),
    ("\\ajLig{??}", "⁇", false),
    ("\\ajLig{?!}", "⁈", false),
    ("\\ajLig{!?}", "⁉", false),
]

let ajLigToLigPatternReplacements: [(String, String)] = [
    ("\\\\ajMasu\\s*", "〼"),
    ("\\\\ajYori\\s*", "ゟ"),
    ("\\\\ajKoto\\s*", "ヿ"),
    ("\\\\ajUta\\s*", "〽"),
    ("\\\\ajCommandKey\\s*", "⌘"),
    ("\\\\ajReturnKey\\s*", "⏎"),
    ("\\\\ajCheckmark\\s*", "✓"),
    ("\\\\ajVisibleSpace\\s*", "␣"),
    ("\\\\ajSenteMark\\s*", "☗"),
    ("\\\\ajGoteMark\\s*", "☖"),
    ("\\\\ajClub\\s*", "♣"),
    ("\\\\ajHeart\\s*", "♡"),
    ("\\\\ajSpade\\s*", "♠"),
    ("\\\\ajDiamond\\s*", "♢"),
    ("\\\\ajvarClub\\s*", "♧"),
    ("\\\\ajvarHeart\\s*", "♥"),
    ("\\\\ajvarSpade\\s*", "♤"),
    ("\\\\ajvarDiamond\\s*", "♦"),
    ("\\\\ajPhone\\s*", "☎"),
    ("\\\\ajPostal\\s*", "〠"),
    ("\\\\ajvarPostal\\s*", "〶"),
    ("\\\\ajSun\\s*", "☀"),
    ("\\\\ajCloud\\s*", "☁"),
    ("\\\\ajUmbrella\\s*", "☂"),
    ("\\\\ajSnowman\\s*", "☃"),
    ("\\\\ajJIS\\s*", "〄"),
    ("\\\\ajHotSpring\\s*", "♨"),
    ("\\\\ajWhiteSesame\\s*", "﹆"),
    ("\\\\ajBlackSesame\\s*", "﹅"),
    ("\\\\ajWhiteFlorette\\s*", "❀"),
    ("\\\\ajBlackFlorette\\s*", "✿"),
    ("\\\\ajHashigoTaka\\s*", "髙"),
    ("\\\\ajTsuchiYoshi\\s*", "𠮷"),
    ("\\\\ajTatsuSaki\\s*", "﨑"),
    ("\\\\ajMayuHama\\s*", "濵"),
]
